### ISSUE TITLE
FSharp.Core dependency

### ISSUE THREAD

**Issue by jochenwezel** [pocketberserker/Diff.Match.Patch#1]
The code requires the FSharp.Core library which hasn't been referenced after adding Diff.Match.Patch to my project using NuGet.

There might be a missing dependency information in the .nuspec file.

**Comment by smoothdeveloper** [comment]
@jochenwezel thanks for reporting the issue, I'll make a PR to fix this.

**Comment by smoothdeveloper** [comment]
@pocketberserker #2 should fix this

**Comment by pocketberserker** [comment]
2.0.0 released.
