### ISSUE TITLE
PatchFromText fails to round trip

### ISSUE THREAD

**Issue by default-kramer** [pocketberserker/Diff.Match.Patch#4]
This example throws an exception. Version is 2.0.1 from NuGet. The exception is System.ArgumentException: Invalid patch string: @@ -5,12 +5,18 @@

const string text1 = "this is some example text";
const string text2 = "this is not really example text";

var patches = DiffMatchPatchModule.Default.PatchMake(text1, text2);
var patchString = DiffMatchPatchModule.Default.PatchToText(patches);
var roundtrip = DiffMatchPatchModule.Default.PatchFromText(patchString);

**Comment by pocketberserker** [comment]
@default-kramer Please tell me your environment(.NET Runtime, CoreCLR or Mono Version).

**Comment by default-kramer** [comment]
This is .NET framework 4.x on Windows 10.

**Comment by pocketberserker** [comment]
I fixed bug and released [2.0.2](https://www.nuget.org/packages/Diff.Match.Patch/2.0.2). Thank you.
